version: '3.4'

services:
  familytreedb:
    image: mongo

  familytree.api:
    image: ${DOCKER_REGISTRY-}familytreeapi
    build:
      context: .
      dockerfile: FamilyTree.API/Dockerfile

volumes:
  mongo_data: